Repository opendistro-for-elasticsearch/anomaly-detection, pull requests merged in 2020-10, with the labels that each got.

#233 CLI: Update Detector Configurations
  cli/cmd/update.go
  cli/internal/controller/ad/ad.go
  cli/internal/controller/ad/ad_test.go
  cli/internal/controller/ad/mocks/mock_ad.go
  cli/internal/entity/ad/ad.go
  cli/internal/gateway/ad/ad.go
  cli/internal/gateway/ad/ad_test.go
  cli/internal/gateway/ad/mocks/mock_ad.go
  cli/internal/handler/ad/ad.go
  cli/internal/handler/ad/ad_test.go
  cli/internal/handler/ad/testdata/update.json
  cli/internal/mapper/ad/ad.go
  cli/internal/mapper/ad/ad_test.go
Labels: feature

#275 bump ad plugin version to 1.11.0
  build.gradle
  src/test/resources/job-scheduler/opendistro-job-scheduler-1.10.1.0-SNAPSHOT.zip
  src/test/resources/job-scheduler/opendistro-job-scheduler-1.11.0.0-SNAPSHOT.zip
Labels: version upgrade

#277 Fix nested field issue
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
Labels: bug

#279 Auto flush checkpoint queue if too many are waiting
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDao.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultTransportAction.java
Labels: enhancement

#272 Added User support for background job and API Transport Actions
  build.gradle
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyResult.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/AbstractSearchAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorRequest.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyRequest.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java
  src/main/plugin-metadata/plugin-security.policy
  src/main/resources/mappings/anomaly-results.json
  src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndicesTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultActionTests.java
  src/test/java/org/elasticsearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java
Labels: enhancement, feature

#280 Adding common-utils dependency from Maven
  build.gradle
  libs/common-utils-1.10.1.0.jar
Labels: dependencies

#276 Add release notes for 1.11.0.0
  release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.11.0.0.md
Labels: documentation

#287 Fix for stats API
  build.gradle
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/CacheBuffer.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/EntityCache.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCache.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/suppliers/ModelsOnNodeSupplier.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractADTest.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/CacheBufferTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCacheTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/stats/ADStatsTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/stats/suppliers/ModelsOnNodeSupplierTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsNodesTransportActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/MultientityResultTests.java
  src/test/java/test/com/amazon/opendistroforelasticsearch/ad/util/MLUtil.java
Labels: bug

#286 Adding new Search Detector Info API
  build.gradle
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestSearchAnomalyDetectorInfoAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoRequest.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoResponse.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoActionTests.java
Labels: enhancement

#290 Fix for get detector API
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportAction.java
Labels: bug

#296 Fix edge case where entities found for preview is empty
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java
Labels: bug

#298 Improve profile API
  build.gradle
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AbstractProfileRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/DetectorModelSize.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/EntityModelSize.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/EntityProfileRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/MemoryTracker.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/Name.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/CacheBuffer.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/EntityCache.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCache.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonName.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/EntityModel.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectorProfile.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectorProfileName.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfile.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfileName.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/EntityState.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ModelProfile.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileRequest.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileResponse.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileNodeRequest.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileNodeResponse.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileRequest.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileResponse.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/MultiResponsesDelegateActionListener.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtils.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractADTest.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/EntityProfileRunnerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/MultiEntityProfileRunnerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportActionTests.java
Labels: bug, enhancement

#302 fix fatal error of missing method parseString
  build.gradle
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDao.java
Labels: bug
