Repository opendistro-for-elasticsearch/anomaly-detection, pull requests merged in 2020-11, with the labels that each got.

#305 remove clock Guice binding
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/MultiEntityResultHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/Throttler.java
Labels: bug

#306 filter out empty value for entity features
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
Labels: bug

#283 Add checkpoint index retention for multi entity detector
  src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/DailyCron.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListener.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/IndexCleanup.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/ModelCheckpointIndexRetention.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListenerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/IndexCleanupTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/ModelCheckpointIndexRetentionTests.java
Labels: enhancement

#309 Fix for upgrading mapping
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
Labels: bug

#312 Fix issue where data hole exists for Preview API
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/EntityColdStarter.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/EntityColdStarterTests.java
Labels: bug

#313 Support ES 7.10.0
  .github/workflows/CI.yml
  .github/workflows/esad-cli-test-and-build-workflow.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.12.0.0.md
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/EntityProfileRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/NodeStateManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListener.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorExecutionInput.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorJob.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyResult.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectorInternalState.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/Entity.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/Feature.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/FeatureData.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/TimeConfiguration.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/AbstractSearchAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestExecuteAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/AnomalyDetectorActionHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/DetectionStateHandler.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/ODFERestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/IndexCleanupTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/e2e/DetectionResultEvalutationIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/MultientityResultTests.java
  src/test/resources/job-scheduler/opendistro-job-scheduler-1.11.0.0-SNAPSHOT.zip
  src/test/resources/job-scheduler/opendistro-job-scheduler-1.12.0.0.zip
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
Labels: odfe-release, version upgrade

#318 Add multi node integration testing into CI workflow
  .github/workflows/CI.yml
Labels: infra
