Repository opendistro-for-elasticsearch/anomaly-detection, pull requests merged in 2020-08, with the labels that each got.

#199 Add badges to AD
  .github/workflows/CI.yml
  README.md
  build.gradle
Labels: documentation

#206 Change Profile List Format
  cli/cmd/profile.go
Labels: enhancement

#203 Allows window size to be set per detector.
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
  src/main/resources/mappings/anomaly-detectors.json
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
Labels: enhancement

#210 not return estimated minutes remaining until cold start is finished
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
Labels: enhancement

#208 Change to use callbacks in cold start
  codecov.yml
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/HashRing.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFPollingTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/TransportState.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/TransportStateManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/DetectionStateHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ColdStartRunner.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractADTest.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFPollingTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/TransportStateManagerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/TransportStateTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/DetectorStateHandlerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/util/ColdStartRunnerTests.java
Labels: enhancement

#216 Install go get outside cli directory
  .github/workflows/esad-cli-test-and-build-workflow.yml
Labels: AnomalyDetection

#219 Include release notes for 1.10.0.0
  build.gradle
  release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.10.0.0.md
Labels: documentation
