Repository opendistro-for-elasticsearch/anomaly-detection, pull requests merged in 2020-12, with the labels that each got.

#327 Adding unit tests for Transport Actions
  build.gradle
  src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/StopDetectorActionTests.java
Labels: enhancement

#331 Adding support for Security Test Framework
  build.gradle
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/SecureADRestIT.java
Labels: enhancement

#334 Updating Readme to include Secure tests
  README.md
Labels: documentation

#340 Fix the profile API returns prematurely.
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/EntityProfileRunner.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfile.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/MultiResponsesDelegateActionListener.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractProfileRunnerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfileTests.java
  src/test/java/org/elasticsearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java
  src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityProfileTests.java
Labels: bug

#341 filter out exceptions which should not be counted in failure stats
  src/main/java/com/amazon/opendistroforelasticsearch/ad/NodeStateManager.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/AnomalyDetectionException.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/ClientException.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/EndRunException.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/LimitExceededException.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/ResourceNotFoundException.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/ADIntegTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorTransportActionTests.java
Labels: enhancement

#353 Fix another case of the profile API returns prematurely
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
  src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityProfileTests.java
Labels: bug
