Repository opendistro-for-elasticsearch/anomaly-detection, pull requests merged in 2020-09, with the labels that each got.

#224 Upgrade from 1.10.0 to 1.10.1
  build.gradle
  src/test/resources/job-scheduler/opendistro-job-scheduler-1.10.0.0-SNAPSHOT.zip
  src/test/resources/job-scheduler/opendistro-job-scheduler-1.10.1.0-SNAPSHOT.zip
Labels: version upgrade

#225 Include release notes for 1.10.1.0
  release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.10.1.0.md
Labels: documentation

#231 CLI: Update Display Strings
  cli/cmd/cat.go
  cli/cmd/create.go
  cli/cmd/delete.go
  cli/cmd/profile.go
  cli/cmd/root.go
  cli/cmd/start_stop.go
Labels: documentation, enhancement

#234 Adding RestActions support for AD Search Rest API's
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/AbstractSearchAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestSearchAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestSearchAnomalyResultAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorTransportAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultTransportAction.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorActionTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultActionTests.java
Labels: enhancement

#237 Adding RestActions support for Detector Stats API
  build.gradle
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestStatsAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/ADStatsResponse.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorAction.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorResponse.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorTransportAction.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorActionTests.java
Labels: enhancement
