Repository opendistro-for-elasticsearch/anomaly-detection, pull requests merged in 2021-02, with the labels that each got.

#358 Change release workflow to use new staging bucket for artifacts
  .github/workflows/CD.yml
Labels: infra

#379 Update draft release notes config
  .github/draft-release-notes-config.yml
Labels: infra

#382 Add release notes for version 1.13.0.0
  release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.13.0.0.md
Labels: documentation

#383 change the backend role filtering to keep consistent with alerting pl…
  src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtils.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtilsTests.java
Labels: enhancement

#387 Update default branch in workflows
  .github/workflows/CI.yml
  .github/workflows/draft-release-notes-workflow.yml
Labels: infra

#390 Backport part of PR 374: enforce init progress to use ASCII explicitly
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
Labels: bug

#391 Backport part of PR 374: enforce init progress to use ASCII explicitly
  src/main/java/com/amazon/opendistroforelasticsearch/ad/AbstractProfileRunner.java
Labels: bug

#389 Extract a new class for entity frequenty tracking
  build.gradle
  docs/entity-priority.pdf
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/CacheBuffer.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCache.java
  src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityTracker.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/NodeStateManagerTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/CacheBufferTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCacheTests.java
  src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityTrackerTests.java
Labels: enhancement
